docker:
  image: yegor256/rultor-image:1.9.0
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
merge:
  script: |-
    pdd --source=$(pwd) --verbose --file=/dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" -e
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors -Pjcabi --settings ../settings.xml
