---
name: mvn
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mvn:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-15]
        java: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: java -version
      - run: mvn -version
      - run: mvn --errors --batch-mode clean install -Pqulice
      - name: Site
        if: runner.os != 'Windows'
        run: mvn --errors --batch-mode -DskipTests -Dinvoker.skip clean site -Psite
